wustl-oncology/analysis-wdls

definitions/tools/filter_vcf_cle.wdl
The structure of this command had a weird side effect.  By doing it this way the command actually comes out to: 
`/usr/bin/perl /usr/bin/docm_and_coding_indel_selection.pl mapq_filtered.vcf.gz "$PWD" filter false`
We mean for filter to be `false` and the filtering done in this script to NOT happen.  But in this command "filter" is in the third argument position, and this is exactly what the Perl script looks for to do the filtering. 
https://github.com/genome/docker-cle/blob/master/docm_and_coding_indel_selection.pl
We don't really have any intention of using this filter.  If we did, this solution wouldn't really work.  But this should produce the correct result if filtering is not desired.  We could probably just drop this step entirely.
If we wanted to fix it more completely, we need …
=> update command so that false is passed in correct position

definitions/rnaseq.wdl, definitions/rnaseq_star_fusion.wdl, definitions/rnaseq_star_fusion_with_xenosplit.wdl, definitions/tools/mark_duplicates_and_sort.wdl
The mark duplicates approach was updated and calls to that from DNA pipelines were updated but these RNA-seq pipelines that also involve mark duplicates were not updated.  The new approach uses sambamba.  This seems to have higher disk usage requirements so that is also being updated here.
=> fixes in rnaseq mark duplicates to accommodate switch to sambamba

definitions/immuno.wdl
=> approach 2 to issue #29

definitions/tools/vep.wdl
Handle issue that affects localization of input files on cluster. This has not been tested on the cloud, but I can't see why it wouldn't work there.
To explain what changes here (because it's complicated), we set the `--custom` string to include a variable in the first parsing step: `$custom_inputs_dir`.  Then, in the second "run vep" step, we populate that variable with the correct inputs directory for that step (as opposed to pointing back to the inputs dir from the first step).
=> use localized copy of vep custom inputs

definitions/tools/extract_hla_alleles.wdl
By adding a Field Separator of `\t`, awk can return empty positional arguments. If it is empty, do nothing. Otherwise, print it.
`awk '{FS="\t";getline;for(n=2;n<=NF-2;n++){if($n==""){}else{printf "HLA-"$n"\n"}}}'`
=> Handling HLA Empty Fields.

definitions/tools/filter_vcf_mapq0.wdl
The updated docker takes a directory as a parameter instead of the filename itself.  The CWL version had already been updated but this one missed the update to 0.5.2 so the update to 0.5.3 needs to include this.
=> Fix for new shell script version of mapq0 filter from 0.5.2

definitions/tools/bam_to_cram.wdl, definitions/tools/docm_gatk_haplotype_caller.wdl, definitions/tools/downsample.wdl, definitions/tools/mutect.wdl, definitions/tools/samtools_flagstat.wdl, definitions/tools/select_variants.wdl, definitions/tools/variants_to_table.wdl
Others in the pipeline are still using older versions, so they'll need to be upgraded first to support this option.
I almost have a successful immuno.wdl run with these changes, but it failed for an unrelated reason that'll need fixing... so the part after all variant filtering hasn't been tested with this yet.
[This is part of #64, but I think it'd be good to do a pass of upgrading some of the aforementioned pipeline steps (especially varscan) before calling that one completed.  The existing changes here are valuable on their own, though, so if this PR looks good we can get the improvements to mutect et al. now while waiting on that.]
=> Set localization_optional on inputs for some GATK and samtools calls.

definitions/immuno.wdl, definitions/tools/extract_hla_alleles.wdl, definitions/tools/hla_consensus.wdl
=> Intuitive file/input names

definitions/tools/filter_vcf_mapq0.wdl
https://hub.docker.com/layers/mgibio/mapq0-filter/v0.5.4/images/sha256-ef5046b3e74bd1689fbf599c2731031213f9436061f791b909bc77779e2137d2?context=explore
=> Update docker image to 0.5.4 for handling of case of 0-depth variant.

definitions/tools/star_fusion_detect.wdl
This backports STAR-Fusion/STAR-Fusion#345 to the version we're currently using in the pipeline.
=> Switch to patched version of star fusion to handle readgroup tag option.

definitions/tools/filter_vcf_cle.wdl, definitions/tools/filter_vcf_docm.wdl
When I was switching images in #79 I saw a few other steps in the the somatic pipeline that were using the "cle" image.  Switching will save a few GB of image pulling per workflow run.
(There are still some pindel steps that use it, but they're not currently a part of the pipeline.)
=> Switch away from "cle" image in VCF filtering steps.

definitions/tools/varscan_process_somatic.wdl, definitions/tools/varscan_somatic.wdl
This required building a newer image with varscan and a newer samtools that supports reading `gs://` URLs.
There are some differences in the varscan output as a result of this change.  The most dramatic change comes not from upgrading to 1.16.1 but from switching from the custom samtools 1.3.1/htslib 1.3.2 combo in the CLE image to any other version I tried (1.3.1 and 1.7). So not sure if there's something special about the combination in the CLE image...
This is part of #64.
=> Add localization optional to varscan somatic.

definitions/tools/vep.wdl
`required_files` (despite the name) is the files that are required for the optional custom annotations.  If none were supplied there will be no entries in the array so we can't assume we will get a path.
=> Only try to look up custom annotations if we have some.

definitions/immuno.wdl, definitions/subworkflows/generate_fda_metrics.wdl, definitions/subworkflows/generate_fda_metrics_for_bam_or_fastqs.wdl, definitions/tools/aligned_seq_fda_stats.wdl, definitions/tools/cram_to_bam.wdl, definitions/tools/fastqc.wdl, definitions/tools/generate_fda_tables.wdl, definitions/tools/md5sum.wdl, definitions/tools/unaligned_seq_fda_stats.wdl
This incorporates some recent additions to the genome/analysis-workflows immuno.cwl pipeline into the WDL version here.
=> Add FDA metrics subworkflow to Immuno pipeline

definitions/immuno.wdl, definitions/rnaseq_star_fusion.wdl
This PR generates a flagstats file that can be found, after pulling results locally, in `.../final_results/qc/tumor_rna`
=> Generating flagstats for RNAseq

definitions/detect_variants.wdl, definitions/immuno.wdl, definitions/somatic_exome.wdl, definitions/somatic_exome_cle.wdl
This is related to 
https://github.com/wustl-oncology/analysis-wdls/issues/112
=> surface gnomad filter threshold to somatic and immuno workflows

definitions/tools/star_fusion_detect.wdl
Increase CPUs for star fusion from 12 to 24.
This process never utilizes preempting. @malachig has requested it just be turned off. We could remove the preempt line entirely since the default is zero but for clarity of the change I have left the line in.
=> changed star fusion cpus to 24 and turned off preempting

definitions/detect_variants.wdl, definitions/detect_variants_nonhuman.wdl, definitions/detect_variants_wgs.wdl, definitions/immuno.wdl, definitions/somatic_exome.wdl, definitions/somatic_exome_cle.wdl, definitions/somatic_exome_nonhuman.wdl, definitions/somatic_wgs.wdl, definitions/subworkflows/filter_vcf.wdl, definitions/subworkflows/filter_vcf_nonhuman.wdl, definitions/subworkflows/fp_filter.wdl, definitions/subworkflows/mutect.wdl, definitions/subworkflows/pindel.wdl, definitions/subworkflows/strelka_and_post_processing.wdl, definitions/subworkflows/varscan.wdl, definitions/subworkflows/varscan_germline.wdl, definitions/subworkflows/varscan_pre_and_post_processing.wdl, definitions/tools/filter_vcf_somatic_llr.wdl, definitions/tools/fp_filter.wdl, definitions/tools/varscan_germline.wdl, definitions/tools/varscan_somatic.wdl, definitions/tumor_only_detect_variants.wdl, definitions/tumor_only_exome.wdl, definitions/tumor_only_wgs.wdl
This is a replacement version of #110 updated to resolve conflicts that have crept up since that PR was originally created.
=> Variant Parameter Cleanup (from PR#110)

definitions/tools/mutect.wdl
Change `localization_optional:true` to false. 
https://github.com/wustl-oncology/analysis-wdls/blob/c89037d4164215c3d73f8fd766f63c92933dcfc2/definitions/tools/mutect.wdl#L19-L22
=> changing localization_optional to false in mutect tool

definitions/tools/pvacfuse.wdl, definitions/tools/pvacseq.wdl
We have encountered consistent failures from BigMHC using 16GB and 8 cpus. This increase seems to resolve the issue.
=> increase memory resources to accommodate BigMHC

definitions/detect_variants_nonhuman.wdl
Proposing a fix for issue: https://github.com/wustl-oncology/analysis-wdls/issues/155
This will correct a typo in strelka variant processing that we believe was impacting results from this variant caller for the non-human variant calling pipeline.
=> fix typo in naming of samples in vcf in strelka variant detection

definitions/immuno.wdl, definitions/subworkflows/pvacseq.wdl
Pass through iedb_retries variable to pvacseq and improve documentation of hla_source_mode.
The input variable `iedb_retries` could be used in tools/pvacseq.wdl and tools/pvacfuse.wdl.  However, in immuno.wdl, it was only getting passed through to pvacfuse. Fixing that.
The input variable `hla_source_mode` was being described as an input to pvacseq, which it is not.  Clarifying that.
=> clarify two immuno inputs

definitions/immuno.wdl, definitions/subworkflows/pvacseq.wdl, definitions/tools/pvacfuse.wdl, definitions/tools/pvacseq.wdl
Still in the process of building the 5.0.1 docker image but should be out later today.
=> Upgrade pvacseq.wdl and pvacfuse.wdl to work with pVACtools 5.0

definitions/tools/bam_readcount.wdl
Update to use new helper image (1.2.1) with updates to: bam-readcount(1.0.1), samtools (1.21), and cyvcf2 (0.31.1)
=> update to use new bam_readcount_helper image
