definitions/detect_variants_wgs.wdl

edit strelka input

---

definitions/rnaseq.wdl
definitions/rnaseq_star_fusion.wdl
definitions/rnaseq_star_fusion_with_xenosplit.wdl
definitions/subworkflows/qc_wgs.wdl
definitions/subworkflows/sequence_to_bqsr.wdl
definitions/tools/mark_duplicates_and_sort.wdl

Adds PR #11 and #14 back to the codebase after their earlier reverts.

Add mark dup changes

---

definitions/tools/mutect.wdl

Tested on both HCC1395 deep exome and a 60x/30x WGS pair, both with mutect scattered 50 ways.

reduces mutect mem to what's actually needed

---

definitions/immuno.wdl

attempting to fix the type issue with the tumor optitype

array type issue

---

definitions/tools/filter_vcf_mapq0.wdl

I made this PR in order to include genome/docker-mapq0-filter#8, but the version here was several behind, so there are other changes coming along, too.

Upgrade mapq0 filter to v0.5.3.

---

.github/workflows/verify.yaml

I'd suggest making this a mandatory check before merging PRs if it seems to be going smoothly.

Also run the WDL verify script on pull requests.

---

definitions/tools/optitype_dna.wdl

- added new script for WDL that includes variables for memory and threads
- added an improved version of WDL.
- created new docker image for testing `(laljorani20/immuno-tools:latest)`
- https://github.com/Layth17/docker-immuno_tools-cwl

Optimizing Optitype

---

definitions/tools/agfusion.wdl

It'd be good to run a test on the dataset that was originally giving us issues before merging this!
Assuming that test works, this closes #68.

Bump AGFusion docker image verison.

---

definitions/immuno.wdl
definitions/rnaseq_star_fusion.wdl
definitions/tools/star_fusion_detect.wdl

https://github.com/STAR-Fusion/STAR-Fusion/wiki
https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#string-interpolation

Star Fusion -- relaxing FFPM filter & extracting preliminary files

---

definitions/tools/generate_fda_tables.wdl

CWL handles this for you by default, but WDL doesn't so I overlooked it. It may not be necessary to quote all of these, but better safe than sorry!
(Even this solution isn't 100% correct. If the string has single quotes in it this is still broken.)
Closes #89.

Need to quote inputs in the script.

---

definitions/immuno.wdl
definitions/subworkflows/pvacseq.wdl

Also output the tabix index for the VCF in pvacseq workflow.

---

definitions/tools/cram_to_bam.wdl

See issue for details of error encountered that this intends to resolve:
https://github.com/wustl-oncology/analysis-wdls/issues/90

increase space request to ensure bam can be created from cram

---

definitions/immuno.wdl
definitions/subworkflows/pvacseq.wdl
definitions/tools/pvacseq.wdl

Reorganization of Immuno.wdl Outputs

---

.dockstore.yml

* This will enable us to easily publish workflows for any branch/tag on the repo.  For the first version, only using `immuno.wdl` but we can add other top-level workflows in the future.
* Initial author list is everyone listed as contributing to this repo on github (except the leylab account).  Notably that doesn't account for any contributors to the CWL analysis-workflows from which these are derived.

Add dockstore yml

---

definitions/tools/mark_duplicates_and_sort.wdl

Increasing space_needed_gb based on issue-
https://github.com/wustl-oncology/analysis-wdls/issues/120
Increasing from
Int space_needed_gb = 10 + round(5*size(bam, "GB")) To
Int space_needed_gb = 20 + round(5*size(bam, "GB"))

Increase space_needed_gb in mark_duplicates_and_sort (Issue #120)

---

definitions/immuno.wdl
definitions/subworkflows/filter_vcf.wdl
definitions/tools/annotate_known_variants.wdl

remove intersect_known_variants and rename filter_known_variants to annotate_known_variants
related to https://github.com/wustl-oncology/analysis-wdls/issues/103

remove intersect_known_variants and rename filter_known_variants

---

definitions/tools/pvacfuse.wdl
definitions/tools/pvacseq.wdl

Docker image is here: https://hub.docker.com/layers/griffithlab/pvactools/4.1.0/images/sha256-bd921160429e5bbb16baeb7eb6d3d6145bf2a9e99b85a3b0a79318536c17e18b?context=explore

Upgrade to pVACtools version 4.1.0

---

definitions/somatic_exome_nonhuman.wdl

Noticed that the CRAM index files were missing from the non-human version of somatic_exome.  Adding them to that version of the pipeline.

add crai index files to the outputs

---

definitions/tools/bqsr.wdl

Fix for: https://github.com/wustl-oncology/analysis-wdls/issues/160

increase disk space needed calc for bqsr-gatherbams step

---

definitions/tools/vep.wdl

Proposing fix to address: https://github.com/wustl-oncology/analysis-wdls/issues/162

increase disk request for vep annotation step

---

definitions/subworkflows/pvacseq.wdl
definitions/tools/add_vep_fields_to_table.wdl
definitions/tools/pvacseq_aggregated_report_to_preferred_transcripts_list.wdl
definitions/tools/vcf_expression_annotator.wdl
definitions/tools/vcf_readcount_annotator.wdl

Needed for https://github.com/wustl-oncology/analysis-wdls/issues/124

Enable new --preferred-transcripts-tsv option in vep-annotation-reporter

---

definitions/immuno.wdl
definitions/subworkflows/pvacseq.wdl
definitions/tools/pvacfuse.wdl
definitions/tools/pvacseq.wdl

Add pVACtools --percentile-threshold-strategy option

---

definitions/immuno.wdl
definitions/somatic_exome.wdl
definitions/somatic_exome_cle.wdl
definitions/somatic_wgs.wdl
definitions/tools/concordance.wdl

Solution for https://github.com/wustl-oncology/analysis-wdls/issues/178 and https://github.com/wustl-oncology/analysis-wdls/issues/164
Add somalier analysis for the RNA samples analyzed as part of immuno pipeline

Concordance threeway
